dist: xenial
sudo: false
latex: false
language: r
r: release
warnings_are_errors: false
cache:
  packages: true
apt_packages:
- libgdal-dev
- libudunits2-dev
branches:
  only:
  - master
git:
  depth: false
r_packages:
- rsconnect
- shiny
- tidyverse
- googlesheets
- shinythemes
- shinyWidgets
script:
- R -f deploy.R
before_install:
- openssl aes-256-cbc -K $encrypted_3c27567c77fe_key -iv $encrypted_3c27567c77fe_iv
  -in googlesheets_token.rds.enc -out googlesheets_token.rds -d
